build using official repo

diff --git a/llvm-bootstrap/PKGBUILD b/llvm-bootstrap/PKGBUILD
--- a/llvm-bootstrap/PKGBUILD
+++ b/llvm-bootstrap/PKGBUILD
@@ -1,6 +1,6 @@
 pkgname=llvm-bootstrap
 pkgdesc="LLVM Toolchain with clang, clang-tools-extra, openmp, compiler-rt, polly, lldb, lld"
-pkgver=20.1.1
+pkgver=20.1.7
 pkgrel=1
 arch=('x86_64')
 url="https://llvm.org/"
@@ -42,9 +42,11 @@ options=('staticlibs' '!lto' '!debug')
 _skip_build_test=y
 _skip_documentation=y
 _extra_build_flags=(
-  -DCMAKE_EXE_LINKER_FLAGS=-Wl,--push-state,/usr/lib/libmimalloc.a,--pop-state 
-  -DCMAKE_CXX_STANDARD=17
-)
+   -DCMAKE_EXE_LINKER_FLAGS=-Wl,--push-state,/usr/lib/libmimalloc.a,--pop-state 
+   -DCMAKE_CXX_STANDARD=17
+   -DLLVM_PARALLEL_LINK_JOBS=20
+   -DLLVM_PARALLEL_COMPILE_JOBS=99
+ )
 _build_documentation=0
 _build_tests=0
 _build_bindings=1
@@ -65,17 +67,20 @@ _patch() {
 
 prepare() {
 
-  mv llvm-project-llvmorg-${pkgver} llvm-project
+  mv "${srcdir:?}/llvm-project-llvmorg-${pkgver}" llvm-project || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Prepare Failed! \E[0m"
+    exit 1
+  )
 
   cd "${srcdir:?}/llvm-project" || (
     echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Prepare Failed! \E[0m"
     exit 1
   )
 
-  # pushd polly/lib/External
-  # chmod +x update-isl.sh
-  # ./update-isl.sh isl-0.27
-  # popd
+  pushd polly/lib/External
+  chmod +x update-isl.sh
+  ./update-isl.sh isl-0.27
+  popd
 
   # Remove CMake find module for zstd; breaks if out of sync with upstream zstd
   rm llvm/cmake/modules/Findzstd.cmake
@@ -89,22 +94,20 @@ build() {
   )
 
 
-  cflags="$CFLAGS -fno-plt -fomit-frame-pointer -fno-semantic-interposition -fallocation-dce -freorder-blocks-algorithm='stc' -freschedule-modulo-scheduled-loops -fsplit-loops -fsplit-paths"
-  cxxflags="$CXXFLAGS -fno-plt -fomit-frame-pointer -fno-semantic-interposition -fallocation-dce -freorder-blocks-algorithm='stc' -freschedule-modulo-scheduled-loops -fsplit-loops -fsplit-paths"
-  ldflags="$LDFLAGS"
+  # cflags="$CFLAGS -fno-semantic-interposition -fsplit-loops -fsplit-paths"
+  # cxxflags="$CXXFLAGS -fno-semantic-interposition -fsplit-loops -fsplit-paths"
+  # ldflags="$LDFLAGS"
   
-  unset CFLAGS
-  unset CXXFLAGS
-  unset LDFLAGS
+  # unset CFLAGS
+  # unset CXXFLAGS
 
   _extra_build_flags+=(
-    -DCMAKE_C_FLAGS="$cflags"
-    -DCMAKE_CXX_FLAGS="$cxxflags"
+    # -DCMAKE_C_FLAGS="$cflags"
+    # -DCMAKE_CXX_FLAGS="$cxxflags"
     -DCMAKE_BUILD_TYPE=Release
     -DCMAKE_INSTALL_PREFIX=/usr
     -DFFI_INCLUDE_DIR="$(pkg-config --variable=includedir libffi)"
     -DLLVM_BINUTILS_INCDIR=/usr/include
-    -DLLVM_STATIC_LINK_CXX_STDLIB=ON
     -DLLVM_HOST_TRIPLE="${CHOST:?}"
     -DLLVM_BUILD_LLVM_DYLIB=ON
     -DLLVM_LINK_LLVM_DYLIB=ON
@@ -114,7 +117,9 @@ build() {
     -DLLVM_ENABLE_FFI=ON
     -DLLVM_ENABLE_PIC=ON
     -DLLVM_USE_PERF=ON
-    -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;lld;compiler-rt;polly;openmp"
+    -DLLVM_ENABLE_PROJECTS="clang;lld;polly"
+    -DLLVM_ENABLE_RUNTIMES='openmp;compiler-rt'
+    -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF
     -DCLANG_LINK_CLANG_DYLIB=ON
     -DCLANG_DEFAULT_PIE_ON_LINUX=ON
     -DLIBOMP_INSTALL_ALIASES=OFF
@@ -125,13 +130,16 @@ build() {
     -Wno-dev
   )
 
-  # if ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
-  #   export LD=ld.lld
-  #   export CC_LD=lld
-  #   export CXX_LD=lld
-  #   export HOSTLD=ld.lld
-  #   _extra_build_flags+=(-DLLVM_ENABLE_LLD=ON)
-  # fi
+  if ${LD:-ld} --version 2>/dev/null | grep -iq "LLD[[:space:]]*[0-9]"; then
+      export LD=ld.lld
+      export CC_LD=lld
+      export CXX_LD=lld
+      export HOSTLD=ld.lld
+      _extra_build_flags+=(
+          -DLLVM_ENABLE_LLD=ON
+          -DLLVM_ENABLE_LTO=Thin
+      )
+  fi
 
   if [ $_build_bindings -eq 1 ]; then
     _extra_build_flags+=(-DLLVM_ENABLE_BINDINGS=ON)
