remove cross project test and move compiler rt to runtime

diff --git a/llvm-all/PKGBUILD b/llvm-all/PKGBUILD
--- a/llvm-all/PKGBUILD
+++ b/llvm-all/PKGBUILD
@@ -79,6 +79,19 @@ prepare() {
     exit 1
   )
 
+  # Clang
+  pushd clang || {
+    echo -e "\E[1;31mpushd - Package Failed!  \E[0m"
+    exit 1
+  }
+  # Fix hardcoded test path
+  sed -i 's/clang-tools-extra/tools\/extra/g' tools/extra/test/clang-doc/enum.cpp
+  sed -i 's/clang-tools-extra/tools\/extra/g' tools/extra/test/clang-doc/namespace.cpp
+
+  popd || {
+    echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
+    exit 1
+  }
 
   # # MLIR
   # ## /usr/bin/ld: cannot find -lLLVMCodeGenTypes: No such file or directory
@@ -140,8 +153,9 @@ build() {
     -DLLVM_ENABLE_RTTI=ON
     -DLLVM_ENABLE_FFI=ON
     -DLLVM_ENABLE_PIC=ON
-    -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;cross-project-tests;lld;lldb;compiler-rt;polly"
-    -DLLVM_ENABLE_RUNTIMES="libcxxabi;pstl;libcxx;openmp"
+    -DLLVM_USE_PERF=ON
+    -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;lld;lldb;polly"
+    -DLLVM_ENABLE_RUNTIMES="libcxxabi;pstl;libcxx;openmp;compiler-rt"
     -DCLANG_LINK_CLANG_DYLIB=ON
     -DCLANG_DEFAULT_PIE_ON_LINUX=ON
     -DLIBCXXABI_USE_LLVM_UNWINDER=OFF
