remove mlir

diff --git a/llvm-all/PKGBUILD b/llvm-all/PKGBUILD
--- a/llvm-all/PKGBUILD
+++ b/llvm-all/PKGBUILD
@@ -9,12 +9,12 @@ license=('custom:Apache 2.0 with LLVM Exception')
 provides=(
   'llvm' "llvm=${pkgver}" 'llvm-libs' 'llvm-ocaml' 'clang' "clang=${pkgver}"
   'clang-analyzer' 'clang-tools-extra' 'polly' 'compiler-rt' 'openmp'
-  'lld' 'lldb' 'libc++' 'libc++abi' 'libc++experimental' 'llvm-bolt' 'mlir'
+  'lld' 'lldb' 'libc++' 'libc++abi' 'libc++experimental' 'llvm-bolt'
   )
 
 replaces=(
   'llvm' 'llvm-libs' 'llvm-ocaml' 'clang' 'clang-analyzer'
-  'clang-tools-extra' 'polly' 'compiler-rt' 'lld' 'lldb' 'openmp' 'mlir'
+  'clang-tools-extra' 'polly' 'compiler-rt' 'lld' 'lldb' 'openmp'
   'libc++' 'libc++abi' 'libc++experimental' 'llvm-bolt'
   )
 
@@ -22,7 +22,7 @@ conflicts=(
   'llvm' 'llvm-libs' 'llvm-ocaml' 'clang' 'clang-analyzer'
   'clang-tools-extra' 'polly' 'compiler-rt' 'lld' 'lldb' 'openmp'
   'llvm-git' 'llvm-libs-git' 'llvm-ocaml-git' 'libc++'
-  'libc++abi' 'libc++experimental' 'llvm-bolt' 'mlir'
+  'libc++abi' 'libc++experimental' 'llvm-bolt'
   )
 
 depends=('libelf' 'libffi' 'libedit' 'libxml2' 'ncurses' 'xz' 'zlib' 'gcc-libs')
@@ -82,22 +82,23 @@ prepare() {
   )
 
 
-  # MLIR
-  ## /usr/bin/ld: cannot find -lLLVMCodeGenTypes: No such file or directory
-  sed -i 's|LLVM_LINK_COMPONENTS|IGNORE_THAT|g' mlir/tools/mlir-tblgen/CMakeLists.txt
+  # # MLIR
+  # ## /usr/bin/ld: cannot find -lLLVMCodeGenTypes: No such file or directory
+  # sed -i 's|LLVM_LINK_COMPONENTS|IGNORE_THAT|g' mlir/tools/mlir-tblgen/CMakeLists.txt
 
-  ## FuncOps.h.inc: No such file or directory
-  pushd mlir  || (
-    echo -e "\E[1;31mpushd - Package Failed!  \E[0m"
-    exit 1
-  )
+  # ## FuncOps.h.inc: No such file or directory
+  # pushd mlir  || (
+  #   echo -e "\E[1;31mpushd - Package Failed!  \E[0m"
+  #   exit 1
+  # )
 
-  curl -L https://github.com/llvm/llvm-project/pull/97885.patch | patch -p2
+  # curl -L https://github.com/llvm/llvm-project/pull/97885.patch | patch -p2
 
-  popd || (
-    echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
-    exit 1
-  )
+  # popd || (
+  #   echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
+  #   exit 1
+  # )
+  # # MLIR DONE
 
   pushd polly/lib/External  || (
     echo -e "\E[1;31mpushd - Package Failed!  \E[0m"
@@ -140,7 +141,7 @@ build() {
     -DLLVM_ENABLE_RTTI=ON
     -DLLVM_ENABLE_FFI=ON
     -DLLVM_ENABLE_PIC=ON
-    -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;cross-project-tests;lld;lldb;compiler-rt;mlir;polly"
+    -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;cross-project-tests;lld;lldb;compiler-rt;polly"
     -DLLVM_ENABLE_RUNTIMES="libcxxabi;pstl;libcxx;openmp"
     -DCLANG_LINK_CLANG_DYLIB=ON
     -DCLANG_DEFAULT_PIE_ON_LINUX=ON
