patch mlir

diff --git a/llvm-all/PKGBUILD b/llvm-all/PKGBUILD
--- a/llvm-all/PKGBUILD
+++ b/llvm-all/PKGBUILD
@@ -80,10 +80,36 @@ prepare() {
     exit 1
   )
 
-  pushd polly/lib/External
+  
+  # MLIR
+  ## /usr/bin/ld: cannot find -lLLVMCodeGenTypes: No such file or directory
+  sed -i 's|LLVM_LINK_COMPONENTS|IGNORE_THAT|g' mlir/tools/mlir-tblgen/CMakeLists.txt
+
+  ## FuncOps.h.inc: No such file or directory
+  pushd mlir  || (
+    echo -e "\E[1;31mpushd - Package Failed!  \E[0m"
+    exit 1
+  )
+
+  curl -L https://github.com/llvm/llvm-project/pull/97885.patch | patch -p2
+
+  popd || (
+    echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
+    exit 1
+  )
+
+  pushd polly/lib/External  || (
+    echo -e "\E[1;31mpushd - Package Failed!  \E[0m"
+    exit 1
+  )
+
   chmod +x update-isl.sh
   ./update-isl.sh isl-0.27
-  popd
+  
+  popd  || (
+    echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
+    exit 1
+  )
 
   if [ -n "$CC" ] && [ -n "$CXX" ]; then
     _extra_build_flags+=(
@@ -121,7 +147,7 @@ build() {
       -DLLVM_ENABLE_FFI=ON
       -DLLVM_ENABLE_PIC=ON
       -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;cross-project-tests;lld;lldb;compiler-rt;mlir;polly"
-      -DLLVM_ENABLE_RUNTIMES="pstl;openmp"
+      -DLLVM_ENABLE_RUNTIMES="libcxxabi;pstl;libcxx;openmp"
       -DCLANG_LINK_CLANG_DYLIB=ON
       -DCLANG_DEFAULT_PIE_ON_LINUX=ON
       -DLIBCXX_INSTALL_MODULES=ON
@@ -138,7 +164,10 @@ build() {
     export CC_LD=lld
     export CXX_LD=lld
     export HOSTLD=ld.lld
-    _extra_build_flags+=(-DLLVM_ENABLE_LLD=ON)
+    _extra_build_flags+=(
+      -DLLVM_ENABLE_LLD=ON
+      -DLLVM_ENABLE_LTO=Thin
+      )
   fi
 
   while true; do
